### ISSUE TITLE
It's could not show under the Android_edit_mode 

### ISSUE THREAD

**Issue by ynheng** [dmytrodanylyk/folding-plugin#16]
dear Dmytrodanylyk ,
This plugin is great , I was exciting when I saw this plugin .
I tried it today , but I found a problem:
It works well under the Project_edit_mode , but not work under the Android_edit_mode,
So will you update it ? 
thanks.

**Comment by Steppschuh** [comment]
Same for me, works fine in the Project view but not in the Android view. Would appreciate it if you could look into this.

Android Studio 2.1.3, Plugin 1.1.1

**Comment by dmytrodanylyk** [comment]
@ynhenggg @Steppschuh 

The Android project view defines its own structure and does not allow modifying the structure through any extensions. Make sure your are in Project structure view, NOT Android.
