### ISSUE TITLE
android视图不分组

### ISSUE THREAD

**Issue by 280455936** [dmytrodanylyk/folding-plugin#19]
project视图，改成android视图的时候，看不到分组效果，能否修正一下？或者有什么解决办法？

**Comment by davidkhala** [comment]
同楼上
It seems author has moved his attention out from this project for a while.
This plugin doesn't work in this display mode
![qq 20170321184245](https://cloud.githubusercontent.com/assets/7227589/24143887/35f49dc6-0e66-11e7-8c8e-eceafd0cf0d0.png)

**Comment by ouyangzn** [comment]
不支持Android视图，都不看readme的么
![qq 20170417095128](https://cloud.githubusercontent.com/assets/8808376/25076462/9e96069c-2353-11e7-9ff1-70980b5bd998.png)
