### ISSUE TITLE
It is not grouping in Android Studio 1.3 RC 4 , 

### ISSUE THREAD

**Issue by vsahu1986** [dmytrodanylyk/folding-plugin#3]
it is showing group and ungroup in Context menu ..

**Comment by dmytrodanylyk** [comment]
Please check http://www.dmytrodanylyk.com/pages/blog/android-file-grouping.html *Limitations* section. 

Are you sure you are in Project structure view, NOT in Android? [Image](http://goo.gl/2U8u3o)

**Comment by vsahu1986** [comment]
Thanks , Yeah Its working , I miss understood , Please close it .
