### ISSUE TITLE
Not working when in Project View - Android

### ISSUE THREAD

**Issue by vanniktech** [dmytrodanylyk/folding-plugin#4]
It works perfectly when my Project View is Project:

![works](https://cloud.githubusercontent.com/assets/5759366/9155914/b5527620-3ec8-11e5-99b1-5101f6b23120.png)

However the moment I switch to Android it does not work anymore:

![android](https://cloud.githubusercontent.com/assets/5759366/9155917/b9f7354e-3ec8-11e5-81a3-03d472d9d598.png)

Even un-grouping and then grouping again does not change it.

**Comment by Rainer-Lang** [comment]
Please read readme 'limitations'

**Comment by vanniktech** [comment]
Ups okay. My bad is there really nothing we can do?

**Comment by dmytrodanylyk** [comment]
Yes, we can't do anything with it.
