### ISSUE TITLE
creating folder only for one item

### ISSUE THREAD

**Issue by alirezaahmadi69** [dmytrodanylyk/folding-plugin#7]
This plugin creates folders that contain only one item. It may not be an issue but it's kind of wired! Why should we group an item. Also adding ability to customize the plugin is really helpful i like to to say for example group files  that starts with fragment_ or activity_ but nothing else. 
Any why, thank you for your great work.

**Comment by dmytrodanylyk** [comment]
You can now use custom patter to do this.
